project:
  type: book

book:
  title: "omega"
  author: "Marco Garofalo"
  date: "2/22/2024"
  chapters:
    - index.qmd
    - sigma_pipi_I0.qmd
    # - intro.qmd
    # - summary.qmd
    - references.qmd

bibliography: references.bib


format:
  html:
    theme: default
    grid:
      sidebar-width: 250px
      body-width:    900px
      margin-width:  250px
      gutter-width:	 1.5em
    max-width: 2000px
    margin: 0
    #html-math-method: mathjax
    # include-in-header: mathjax.html
    html-math-method: katex


